### ISSUE TITLE
Unable to query number of CUDA devices/Driver/library version mismatch 

### ISSUE THREAD

**Issue by Epictek** [aaronmboyd/docker-xmrMiner#1]
Trying to run this on Void Linux, So far having no luck any ideas?

Docker:
```
docker run --device /dev/nvidia0:/dev/nvidia0 --device /dev/nvidiactl:/dev/nvidiactl --device /dev/nvidia-uvm:/dev/nvidia-uvm  **** docker_worker_1 --donate=1
    *** xmrMiner 0.2.1 (64 bit) for NVIDIA GPUs by psychocrypt 
    *** Built with GCC 5.4  using the Nvidia CUDA Toolkit 8.0
-----------------------------------------------------------------
[2017-07-31 01:25:42] Unable to query number of CUDA devices!

```

```
docker run -it --device /dev/nvidia0:/dev/nvidia0 --device /dev/nvidiactl:/dev/nvidiactl --device /dev/nvidia-uvm:/dev/nvidia-uvm  --entrypoint /bin/bash xmrminer
root@abbce2f28c40:/xmrMiner/build# nvidia-smi 
Failed to initialize NVML: Driver/library version mismatch
```

Host:
```
~ ❯❯❯ nvidia-smi                                                                                                                                     ⏎
Mon Jul 31 02:25:06 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 381.22                 Driver Version: 381.22                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 660 Ti  Off  | 0000:01:00.0     N/A |                  N/A |
| 10%   39C    P5    N/A /  N/A |    416MiB /  1996MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 970     Off  | 0000:07:00.0     Off |                  N/A |
|  0%   34C    P8     9W / 180W |      2MiB /  4037MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0                  Not Supported                                         |
+-----------------------------------------------------------------------------+

```

**Comment by aaronmboyd** [comment]
Noted this happened on my host that I originally build the image on now as well. I'm investigating. I suspect the latest NVIDIA update has broken it somehow, or the isolation/containerization with Docker I was hoping to give is not really possible. Because it seems that you need to have CUDA installed on the host regardless - so you can pass the correct devices to the container, but I'm not sure yet.

**Comment by aaronmboyd** [comment]
@Epictek 

## The problem
As I mentioned, this problem was also occurring on my host, with a similar GPU - GeForce 550 Ti, with a compute capacity of 2.1, a bit older than yours. 

This Docker image was originally tested successfully in mid July on my host (Ubuntu x86_64). My current theory is that a recent NVIDIA driver update (late July 2017) deprecated GPUs with a low compute capacity ([the  660 Ti is 3.0](https://developer.nvidia.com/cuda-gpus)) for certain CUDA functions, or the driver update caused incompatibility with the CUDA 8.0 drivers used in the xmrminer image.

There was a fair bit of evidence that this error is due to mismatched CUDA/NVIDIA installs;

* https://devtalk.nvidia.com/default/topic/1000667/failed-to-initialize-nvml-driver-library-version-mismatch/
* https://devtalk.nvidia.com/default/topic/994457/driver-library-version-mismatch-after-updating-drivers-to-version-375-26/
* https://stackoverflow.com/questions/43022843/nvidia-nvml-driver-library-version-mismatch

## I was able to resolve this by:

* Note: I realise you're using _Void Linux_, translate to your own package manager commands as needed, but this is what got it working again in Ubuntu 16.04 for me.

1. First switching to the X.Org X server open source graphics driver (via _Software & Updates_, *Additional Drivers* tab)
2. Removing all my NVIDIA drivers; `sudo apt-get remove nvidia*`
3. Removing all my CUDA drivers; `sudo apt-get remove cuda*`
4. Removing any packages from the _Software & Updates_, *Other Software* tab, relating to the CUDA install. (Or you can remove from `/etc/apt/sources.list`). I had previously added a package reference to http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64, which I now unticked.
5. Purge; `sudo apt-get autoremove`
6. Restart
7. Now, install the xenial package `nvidia-cuda-toolkit`, which also installs the NVIDIA driver compatibile with that CUDA package; `sudo apt-get install nvidia-cuda-toolkit`
8. Verify output of `nvcc -V` and `nvidia-smi`. Check _Software & Updates_ and switch to the 375.66 driver if necessary.
Mine appears as;
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
```
and
```
NVIDIA-SMI 375.66                 Driver Version: 375.66
```
## Changes
If you look at the [package details for xenial](https://launchpad.net/ubuntu/+source/nvidia-cuda-toolkit) it appears that CUDA is not yet up to version 8.0 for this maintained package, so I may have made a mistake forcing CUDA 8.0 on the Docker image which is based on 16.04.

So what I'm going to do now is change the Dockerfile to not force 8.0 and simpy use `nvidia-cuda-toolkit`. My clean up / fresh install worked for me, but your mileage may vary. I'll keep you updated.

My hope with this project was to have the miner fully containerised so the host doesn't even need NVIDIA/CUDA drivers at all. This doesn't look to be the case and I might investigate [nvidia-docker](https://github.com/NVIDIA/nvidia-docker) instead, which may solve this problem.

**Comment by Epictek** [comment]
Thanks for the very detailed response. I tried downgrading the nivdia drivers but can't seem to build it against the latest linux kernel. Looks like I'll be mining in a VM using pci-passthrough for now :/

**Comment by aaronmboyd** [comment]
I actually spent a fair bit of time last night and realised that [nvidia-docker](https://github.com/NVIDIA/nvidia-docker) Docker images have solved many of the problems I was trying to resolve from scratch. I've updated the image to use **nvidia/cuda** as the base but have not yet pushed to this repos. 

I realise also, there is a compatibility matrix with your NVIDIA driver and CUDA version (which is 8.0 in my image).

Check this link to see which version you need: https://github.com/NVIDIA/nvidia-docker/wiki/CUDA#requirements

**Comment by aaronmboyd** [comment]
@Epictek 

Please pull the latest image and try this now. Follow the instructions in the README.md as I've changed the base image to be from nvidia/cuda.

**Comment by Epictek** [comment]
Docker build for void is currently broken so nvidia-docker doesn't work. Will report back once they fix docker.
https://github.com/voidlinux/void-packages/issues/7230

**Comment by Epictek** [comment]
Fixed https://github.com/voidlinux/void-packages/commit/2cde47b0a6d010805b2d76370c27830c0b517094
